#stage 1
FROM golang:1.16.3 AS builder
WORKDIR /go/src
ENV PATH="/go/bin:${PATH}"
COPY . .
RUN GOOS=linux go build -ldflags="-s -w" -o /go/bin/app
RUN chmod +x /go/bin/app


#stage 2 - build a small image
FROM scratch
WORKDIR /home
COPY --from=builder /go/bin/app .
ENTRYPOINT ["./app"]

